fix ExecutorEventSchedulerTest race-condition
Rarely, this is hit:
```
[INFO] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.028 s <<< FAILURE! - in com.ocadotechnology.event.scheduling.ExecutorEventSchedulerTest
[INFO] [ERROR] testGetQueueSize  Time elapsed: 0.026 s  <<< FAILURE!
[INFO] org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
[INFO] 	at com.ocadotechnology.event.scheduling.ExecutorEventSchedulerTest.testGetQueueSize(ExecutorEventSchedulerTest.java:53)
[INFO]
```

This change forces synchronisation between executor thread and test thread to remove racing.

#333

(cherry picked from commit e384a131023b27187b57ab39e56138ee21cf8cc5)