#190 Add a precondition with message if Subscriber doesn't include parameter
At present you get an ArrayIndexOutOfBoundsException if you add a
Subscribe-annotated method to a Subscriber that doesn't have a single
parameter:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

	at com.ocadotechnology.notification.NotificationBus.collectSubscribingTypes(NotificationBus.java:98)
	at com.ocadotechnology.notification.NotificationBus.addHandler(NotificationBus.java:76)
	at com.ocadotechnology.notification.Broadcaster.addHandler(Broadcaster.java:101)
```
This changeset makes that an IllegalArgumentException precondition,
outlining the method that needs fixing:

```
java.lang.IllegalArgumentException: @Subscribe-annotated handler method invalidHandler should have a single parameter
        at ...
```

(cherry picked from commit 3ec72a16dcbd68205c55f45f1e82da6d8675a5a4)